### ISSUE TITLE
// clone the bmp085 project into the folder below

### ISSUE THREAD

**Issue by SpiritAmalthea** [lucavb/homebridge-bmp180#1]
Which one bmp085 project have library what needed for this plugin?

**Comment by lucavb** [comment]
That would be this one. I did it because when I wrote this plugin, there was an issue with the i2c package for raspberry pis, which is a dependency of this plugin.

https://www.npmjs.com/package/bmp085

**Comment by SpiritAmalthea** [comment]
Thank you. Right this i am aleady used :)
